# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUpVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u6295\u7968\u65e5\u671f')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Comment', verbose_name='\u88ab\u6295\u7968\u7684comment')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u7968\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5')),
                ('source', models.CharField(max_length=255, verbose_name='\u6765\u6e90')),
                ('points', models.IntegerField(verbose_name='\u8bc4\u5206')),
                ('hidden', models.BooleanField(verbose_name='\u662f\u5426\u9690\u85cf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemUpVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u6295\u7968\u65e5\u671f')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item', verbose_name='\u88ab\u6295\u7968\u7684\u7269\u4ef6')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u7968\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='voters',
            field=models.ManyToManyField(through='items.ItemUpVote', to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u7968\u8005'),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.Item', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='items.Comment', verbose_name='\u9488\u5bf9\u54ea\u4e2acomment\u7684comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(through='items.CommentUpVote', to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u7968\u8005'),
        ),
    ]
