# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='items.Comment', verbose_name='\u9488\u5bf9\u54ea\u4e2acomment\u7684comment'),
        ),
    ]
